# Generated by Django 5.0.1 on 2024-01-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_alter_crew_options_train_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["journey", "cargo", "seat"]},
        ),
        migrations.AlterField(
            model_name="journey",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_routes",
                to="station.route",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_trains",
                to="station.train",
            ),
        ),
    ]
