# Generated by Django 5.0.1 on 2024-01-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_alter_ticket_options_alter_journey_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trains",
                to="station.traintype",
            ),
        ),
    ]
