# Generated by Django 5.0.1 on 2024-01-17 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_alter_train_train_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["-departure_time", "train__name"]},
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["name"]},
        ),
    ]
