# Generated by Django 5.0.1 on 2024-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0006_alter_journey_options_alter_train_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("destination", "source")},
        ),
    ]
